# Use a mesma imagem base para consistência
FROM pytorch/pytorch:2.8.0-cuda12.9-cudnn9-runtime

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os requisitos e instalar as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o script de teste
COPY test.py .

# Comando para executar o script de teste
CMD ["python", "test.py"]